import { StyleSheet, Dimensions } from "react-native";
import Color from "../../../../assets/Color";

const { width, height } = Dimensions.get("screen");
const styles = StyleSheet.create({
  screen: { backgroundColor: Color.black, flex: 1 },
  scroll: { height: 15000 },
  carImages: { width: Dimensions.get("window").width, height: 250 },
  carImage: { width: "100%", height: "100%" },
  SmallCarCon: {
    width: Dimensions.get("window").width * 0.8,
    alignSelf: "center",
    bottom: 36,
    padding: 16,
    backgroundColor: Color.darkgrey,
    borderRadius: 14,
  },
  smallcarImages: { width: 100, height: 60, marginHorizontal: 8 },
  BrandInfo: { paddingHorizontal: 16, bottom: 36 },
  BrandView: { width: 80, height: 80, alignSelf: "center" },
  Brand: { width: "100%", height: "100%", alignSelf: "center" },
  BrandName: {
    alignSelf: "center",
    fontFamily: "black",
    fontSize: 28,
    color: Color.white,
    marginBottom: 10,
  },
  BrandRate: {
    alignSelf: "center",
    fontFamily: "semibold",
    fontSize: 20,
    color: Color.white,
  },
  header: {
    marginBottom: 10,
    fontSize: 24,
    fontFamily: "semibold",
    color: Color.lightgreen,
    paddingLeft: 12,
  },
  AboutTheCar: {
    marginBottom: 10,
    marginTop: 14,
    fontSize: 24,
    fontFamily: "semibold",
    color: Color.lightgreen,
    paddingLeft: 12,
  },
  description: {
    width: Dimensions.get("window").width * 0.98,
    padding: 8,
    marginVertical: 8,
  },
  descText: {
    textAlign: "center",
    fontSize: 18,
    alignSelf: "center",
    color: Color.white,
    fontFamily: "book",
  },
  features: {
    alignSelf: "center",
    justifyContent: "center",
    marginBottom: 20,
    borderRadius: 20,
    width: Dimensions.get("window").width * 0.88,
    height: 200,
  },
  featuresText: {
    fontSize: 18,
    fontFamily: "header",
    color: Color.white,
    alignSelf: "center",
    textAlign: "center",
  },
  Constyle: {
    alignSelf: "center",
    justifyContent: "center",
  },
  BoxView: {
    padding: 12,
    backgroundColor: Color.darkgrey,
    borderRadius: 12,
    marginHorizontal: 8,
  },
  EveelLogo: { height: 35, width: 35 },
  Variants: {
    fontFamily: "black",
    color: Color.white,
    fontSize: 16,
  },
  BrandVar: { fontFamily: "medium", color: "white", fontSize: 14 },
  price: {
    fontFamily: "black",
    color: Color.lightgreen,
    fontSize: 18,
  },
  ColorView: { marginBottom: 50, marginTop: 20 },
  ColorBoxView: {
    padding: 12,
    backgroundColor: Color.darkgrey,
    borderRadius: 8,
    marginHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  ColorName: {
    width: 80,
    alignSelf: "center",
    marginTop: 8,
    fontFamily: "black",
    color: Color.white,
    fontSize: 18,
  },
  ModalView: {
    height: Dimensions.get("window").height * 0.75,
    backgroundColor: Color.black,
    padding: 10,
  },
  heart: {
    margin: 20,
    backgroundColor: Color.darkgrey,
    padding: 8,
    borderRadius: 20,
    alignSelf: "center",
    overflow: "hidden",
  },
  readMore: {
    fontFamily: "bold",
    color: Color.lightgreen,
    textAlign: "center",
    fontSize: 20,
    padding: 10,
  },
  button: {
    width: "90%",
    padding: 8,

    flexDirection: "row",
    borderRadius: 8,
    alignSelf: "center",
    justifyContent: "space-around",
    marginVertical: 8,
  },
  ModalHeader: {
    marginTop: 16,
    fontSize: 20,
    fontFamily: "header",
    color: Color.lightgreen,
    alignSelf: "center",
  },
  AndSy: { fontFamily: "medium", fontSize: 24 },
  ColorModalView: {
    height: Dimensions.get("window").height * 0.6,
    backgroundColor: Color.black,
    padding: 10,
  },
  ColorModal: {
    width: Dimensions.get("window").width * 0.8,
    alignSelf: "center",
    marginHorizontal: 20,
  },
  ColorModalImg: {
    width: Dimensions.get("window").width * 0.8,
    height: Dimensions.get("window").height * 0.4,
  },
  ColorIndex: { fontSize: 30, color: Color.lightgreen, fontFamily: "black" },
  ColorModalName: { fontSize: 24, fontFamily: "black", color: Color.white },
  color: { height: 80, width: 80 },
});
export default styles;
